package externalidp

import (
	"context"
	"errors"
)

// Errors returned by providers.
var (
	ErrUnknownProvider = errors.New("unknown provider type")
	ErrInvalidConfig   = errors.New("invalid provider config")
	ErrAuthFailed      = errors.New("external auth failed")
	ErrStateMismatch   = errors.New("state mismatch (possible CSRF)")
)

// AuthorizeRequest carries the inputs each provider needs to mint its
// authorization URL (the URL we 302 the user to on the IdP's site).
type AuthorizeRequest struct {
	// State is generated by the gateway, persisted in Redis under a short TTL,
	// and verified back on the callback to prevent CSRF.
	State string
	// RedirectURI is the absolute callback URL on MXID
	// (e.g. https://mxid.example.com/api/v1/portal-public/auth/external/lark/callback).
	RedirectURI string
	// Login hint (email/username/openid) — optional, providers ignore when absent.
	LoginHint string
}

// AuthorizeResponse is what the gateway returns to the browser. The vast
// majority of providers return a single URL to redirect to; we don't bother
// with the form-post style yet.
type AuthorizeResponse struct {
	URL string
}

// CallbackRequest is the data the gateway extracts from the IdP's callback
// query string and hands to the provider for token exchange.
type CallbackRequest struct {
	Code        string
	State       string
	RedirectURI string
}

// ExternalIdentity is the normalised user profile returned by Provider.Exchange.
//
// Fields mirror mxid_user_identity columns; the gateway uses them to upsert
// the mapping (provider_id + external_id) and either return the linked
// mxid_user.id (if the binding exists) or auto-provision a new local user
// when ExternalIDP.AutoCreate is true.
type ExternalIdentity struct {
	// ProviderType + ProviderID + ExternalID together form a unique key.
	// ProviderType matches ExternalIDP.Type ("lark" etc).
	// ProviderID matches ExternalIDP.Code (so the same type with multiple
	// configured tenants can coexist without collision).
	ProviderType string
	ProviderID   string
	// ExternalID is the IdP-local user identifier (Lark open_id, GitHub user.id, ...).
	// MUST be stable across the user's lifetime in that IdP.
	ExternalID string

	// Friendly fields used for auto-provisioning the local user.
	Username    string
	DisplayName string
	Email       string
	Phone       string
	Avatar      string

	// Raw is the full attribute set returned by the IdP (already JSON-decoded).
	// Persisted in mxid_user_identity.extra so admins can inspect later.
	Raw map[string]any
}

// Provider is the contract every external IdP implementation fulfils.
//
// Provider instances are constructed by a Factory from a serialised
// ExternalIDP row — they are stateless beyond the config decoded at build
// time, so they can be cached and reused across requests.
type Provider interface {
	// Type returns the provider type constant (Type*). Used by the registry
	// to look up the matching factory.
	Type() string
	// Authorize returns the URL to redirect the user-agent to on the IdP.
	Authorize(ctx context.Context, req *AuthorizeRequest) (*AuthorizeResponse, error)
	// Exchange swaps the callback code for an access token and fetches the
	// user profile. Returns a normalised ExternalIdentity on success.
	Exchange(ctx context.Context, req *CallbackRequest) (*ExternalIdentity, error)
}

// Factory builds a Provider from a serialised ExternalIDP row. Each
// concrete provider (Lark, GitHub, ...) registers a factory in its file's
// init() into the package-level Registry.
type Factory func(idp *ExternalIDP) (Provider, error)
