{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mxid.fullname" . }}
  labels:
    {{- include "mxid.labels" . | nindent 4 }}
type: Opaque
stringData:
  MXID_DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  MXID_REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  MXID_CRYPTO_KEY_ENCRYPTION_KEY: {{ .Values.secrets.cryptoKeyEncryptionKey | quote }}
{{- end }}
